require('../infrastructure')
require('./fixture')
global.$ = require('jquery')
global.t10 = require('t10')
global.basepath = '/'
global.capsid = require('capsid')
global.capsidScrollLock = require('capsid-scroll-lock')
global.capsidJquery = require('capsid/jquery')
global.capsidJquery(capsid, $)
global.domain = require('../domain')
global.Action = require('../const/action-types')
require('../common/atoms')
